# -*- coding: utf-8 -*-
"""Differential Robot Kinematic Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bk9AVvOc6qEAfJVLpihiWbUjKxj8qJG7
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

class Diff_Robot():
    def __init__(self):
        self.xc = 0
        self.yc = 0
        self.theta = np.pi/2
        self.r = 0.02  #radius of Wheel
        self.L = 0.1   # distance between wheels
        
        self.sample_time = 0.01
        
    def reset(self):
        self.xc = 0
        self.yc = 0
        self.theta = 0
        self.delta = 0
        self.beta = 0
 
class Diff_Robot(Diff_Robot):
    def step(self, wL, wR):
            
            Vx = (self.r*np.cos(self.theta)*(wL+wR))/2
            Vy = (self.r*np.sin(self.theta)*(wL+wR))/2
            thetadot = (wR*self.r - wL*self.r)/self.L
            self.xc = self.xc + Vx*self.sample_time
            self.yc = self.yc + Vy*self.sample_time
            self.theta = self.theta + thetadot*self.sample_time
             
            pass

sample_time = 0.01
time_end = 3
model = Diff_Robot()
 
t_data = np.arange(0,time_end,sample_time)
x_data = np.zeros_like(t_data)
y_data = np.zeros_like(t_data)
theta_data = np.zeros_like(t_data)
 
for i in range(t_data.shape[0]):
    x_data[i] = model.xc
    y_data[i] = model.yc
    theta_data[i] = model.theta
    model.step(5, 100)

#plt.axis('equal')
plt.plot(t_data, x_data,label='Differential Model')
plt.legend()
plt.show()